/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import DebugModal from './DebugModal';

interface DebugModalsProps {
  // Material debug modal
  isMaterialDebugModalOpen: boolean;
  onCloseMaterialDebugModal: () => void;
  materialDebugUrl: string | null;
  seamlessTextureUrl: string | null;
  materialInputImageUrl: string | null;
  seamlessTexturePrompt: string | null;
  
  // Scene debug modal
  isSceneDebugModalOpen: boolean;
  onCloseSceneDebugModal: () => void;
  sceneDebugUrl: string | null;
  sceneAreaDescription: string | null;
  
  // Result debug modal
  isResultDebugModalOpen: boolean;
  onCloseResultDebugModal: () => void;
  resultImageUrl: string | null;
  resultDebugInputImageUrl: string | null;
  debugPrompt: string | null;
}

/**
 * Component grouping all debug modals for the application
 */
const DebugModals: React.FC<DebugModalsProps> = ({
  isMaterialDebugModalOpen,
  onCloseMaterialDebugModal,
  materialDebugUrl,
  seamlessTextureUrl,
  materialInputImageUrl,
  seamlessTexturePrompt,
  isSceneDebugModalOpen,
  onCloseSceneDebugModal,
  sceneDebugUrl,
  sceneAreaDescription,
  isResultDebugModalOpen,
  onCloseResultDebugModal,
  resultImageUrl,
  resultDebugInputImageUrl,
  debugPrompt
}) => {
  return (
    <>
      <DebugModal 
        isOpen={isMaterialDebugModalOpen} 
        onClose={onCloseMaterialDebugModal}
        imageUrl={seamlessTextureUrl}
        materialImageUrl={materialInputImageUrl}
        prompt={seamlessTexturePrompt}
        title="Material Source Debug"
        description="Input image with marker, generated seamless texture, and the prompt used"
        showMaterialSection={true}
        showPromptSection={true}
        aiResponse="Generated seamless texture based on the material characteristics from the marked area"
        aiResponseTitle="Generated Result"
      />
      
      <DebugModal 
        isOpen={isSceneDebugModalOpen} 
        onClose={onCloseSceneDebugModal}
        imageUrl={sceneDebugUrl}
        title="Target Area Detection Debug"
        description="The target area marked with red border for material application"
        showPromptSection={false}
        aiResponse={sceneAreaDescription}
        aiResponseTitle="AI Scene Area Analysis"
      />
      
      <DebugModal 
        isOpen={isResultDebugModalOpen} 
        onClose={onCloseResultDebugModal}
        imageUrl={resultImageUrl}
        materialImageUrl={resultDebugInputImageUrl}
        prompt={debugPrompt}
        title="Generation Result Debug"
        description="Input image, output image, and the prompt used for generation"
        showMaterialSection={true}
        showPromptSection={true}
        aiResponse="Final result generated by applying seamless texture to the purple-filled areas"
        aiResponseTitle="Generated Result"
      />
    </>
  );
};

export default DebugModals;